/*  EECS 348 Assignment 2
 *  This program is an email priority queue implemented using a MaxHeap.
 *  Emails are sorted by sender priority category and then by date (newest first).
 *  Supports EMAIL, NEXT, READ, and COUNT commands from stdin.
 *  This finalized code evaluates and refines buffer management and parsing
 *  logic generated by LLMs to handle edge cases and long inputs reliably.
 *
 *  Collaborators: Luke Tidball, Gemini 3.6 Flash
 */

#include <stdio.h> // These three lines import various libraries
#include <stdlib.h> // 
#include <string.h>

#define MAX_LINE 1024 // Initially 256. Increased input line buffer to prevent input line truncation

typedef struct { // Begins definition of the Email structure type
    char sender[32]; // Array buffer storing sender category string
    char subject[512]; // Expanded array buffer to hold exceptionally long subjects
    char date[16]; // Array buffer storing date string
} Email; // Closes struct definition

typedef struct {
    Email *data;
    int size;
    int capacity;
} MaxHeap;

// Helper function to map sender category string to integer priority score.
// Higher number = higher priority.
int get_category_priority(const char *sender) {
    if (strcmp(sender, "Boss") == 0) return 5;
    if (strcmp(sender, "Subordinate") == 0) return 4;
    if (strcmp(sender, "Peer") == 0) return 3;
    if (strcmp(sender, "ImportantPerson") == 0) return 2;
    return 1; // OtherPerson
}

// Converts MM-DD-YYYY (or M-D-YYYY string) into YYYYMMDD integer for chronological comparison
int date_to_int(const char *date) { // Function parsing a date string into an integer value
    int m = 0, d = 0, y = 0; // Declares local integer variables for month, day, and year
    if (sscanf(date, "%d-%d-%d", &m, &d, &y) != 3) { // Parses integer values directly from hyphen-separated string
        return 0; // Fallback value if format fails
    } // Closes format check
    return y * 10000 + m * 100 + d; // Returns a single integer formatted chronologically as YYYYMMDD
} // Closes date_to_int function block

// Returns > 0 if email A has higher priority than email B, < 0 if B > A, 0 if equal
int compare_emails(const Email *a, const Email *b) {
    int prioA = get_category_priority(a->sender);
    int prioB = get_category_priority(b->sender);

    if (prioA != prioB) {
        return prioA - prioB;
    }
    // Same category: newer date wins
    return date_to_int(a->date) - date_to_int(b->date);
}

// Initialize the Heap
MaxHeap* create_heap(int initial_capacity) {
    MaxHeap *heap = (MaxHeap*)malloc(sizeof(MaxHeap));
    heap->capacity = initial_capacity;
    heap->size = 0;
    heap->data = (Email*)malloc(sizeof(Email) * heap->capacity);
    return heap;
}

void swap(Email *a, Email *b) {
    Email temp = *a;
    *a = *b;
    *b = temp;
}

// Heapify up when inserting
void heapify_up(MaxHeap *heap, int index) {
    while (index > 0) {
        int parent = (index - 1) / 2;
        if (compare_emails(&heap->data[index], &heap->data[parent]) > 0) {
            swap(&heap->data[index], &heap->data[parent]);
            index = parent;
        } else {
            break;
        }
    }
}

// Heapify down when extracting max
void heapify_down(MaxHeap *heap, int index) {
    int largest = index;
    int left = 2 * index + 1;
    int right = 2 * index + 2;

    if (left < heap->size && compare_emails(&heap->data[left], &heap->data[largest]) > 0) {
        largest = left;
    }
    if (right < heap->size && compare_emails(&heap->data[right], &heap->data[largest]) > 0) {
        largest = right;
    }
    if (largest != index) {
        swap(&heap->data[index], &heap->data[largest]);
        heapify_down(heap, largest);
    }
}

void insert_email(MaxHeap *heap, Email e) {
    if (heap->size == heap->capacity) {
        heap->capacity *= 2;
        heap->data = (Email*)realloc(heap->data, sizeof(Email) * heap->capacity);
    }
    heap->data[heap->size] = e;
    heapify_up(heap, heap->size);
    heap->size++;
}

void read_email(MaxHeap *heap) {
    if (heap->size == 0) return;
    
    heap->data[0] = heap->data[heap->size - 1];
    heap->size--;
    if (heap->size > 0) {
        heapify_down(heap, 0);
    }
}

void free_heap(MaxHeap *heap) {
    free(heap->data);
    free(heap);
}

int main(void) {
    MaxHeap *heap = create_heap(10);
    char line[MAX_LINE];

    while (fgets(line, sizeof(line), stdin) != NULL) {
        // Strip trailing newline character
        line[strcspn(line, "\r\n")] = 0;
        if (strlen(line) == 0) continue;

        if (strncmp(line, "EMAIL ", 6) == 0) {
            Email e;
            char *token_str = line + 6;
            
            // Parse comma-delimited fields with matched field width limits
            sscanf(token_str, "%31[^,],%511[^,],%15s", e.sender, e.subject, e.date); // Parses fields using expanded width caps
            
            // Trim leading/trailing whitespace if present
            char *s = e.sender;
            while(*s == ' ') s++;
            
            insert_email(heap, e);
        } 
        else if (strcmp(line, "COUNT") == 0) {
            printf("There are %d emails to read.\n", heap->size);
        } 
        else if (strcmp(line, "NEXT") == 0) {
            if (heap->size > 0) {
                printf("Next email:\n");
                printf("Sender: %s\n", heap->data[0].sender);
                printf("Subject: %s\n", heap->data[0].subject);
                printf("Date: %s\n", heap->data[0].date);
            }
        } 
        else if (strcmp(line, "READ") == 0) {
            if (heap->size > 0) {
                read_email(heap);
            }
        }
    }

    free_heap(heap);
    return 0;
}